baseURL = "https://today-calm.github.io/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "TC 的空间"

theme = "DoIt"

[params]
  [params.header]
    [params.header.title]
      name = "TC 的空间"
      pre = "<i class='fas fa-home'></i>"

  [params.footer]
    enable = true
    # 是否显示 Hugo 和主题信息
    hugo = true
    # 托管服务信息 (支持 HTML 格式)
    hostedOn = '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>' 
    copyright = true
    since = 2023

  # 主页配置
  [params.home]
    [params.home.profile]
      enable = true
      # 主页显示头像的 URL
      # 将你的头像文件放置于 static 或者 assets 目录下
      # 文件路径是相对于 static 或者 assets 目录的
      avatarURL = "/moon.jpg"
      subtitle = "信心是发动机，热情是燃烧剂。"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = false
    [params.home.posts]
      enable = true
      paginate = 5

  # 文章页面配置
  [params.page]
    # 是否使用 ruby 扩展语法
    ruby = false
    # 是否使用 fraction 扩展语法
    fraction = false
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # KaTeX 数学公式
    [params.page.math]
      enable = false
    # 相关文章推荐配置
    [params.page.related]
      enable = false
    # 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否保持使用文章前面的静态目录
      # 必须显示指定！
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = false
    # 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 20
    # 表格配置
    [params.page.table]
      # 是否开启表格排序
      sort = true
    [params.page.header]
      # 是否开启标题自动编号
      [params.page.header.number]
        enable = true
        [params.page.header.number.format]
          h2 = "{h2} {title}"
          h3 = "{h2}.{h3} {title}"
          h4 = "{h2}.{h3}.{h4} {title}"
          h5 = "{h2}.{h3}.{h4}.{h5} {title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

  [params.search]
    enable = true
    # 搜索引擎的类型 ("algolia", "fuse")
    type = "fuse"
    [search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.1
      distance = 100
      ignoreLocation = true
      useExtendedSearch = false
      ignoreFieldNorm = false

# 作者配置
[author]
  name = " "

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "归档"
    url = "/posts/"
    pre="<i class='fas fa-archive fa-sm'></i>"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    pre="<i class='fas fa-icons fa-sm'></i>"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    pre = "<i class='fas fa-tags fa-sm'></i>"
    weight = 3
  [[menu.main]]
    identifier = "list"
    name = "清单"
    url = "/categories/清单/"
    pre = "<i class='fas fa-list fa-sm'></i>"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    pre="<i class='fas fa-paper-plane fa-sm'></i>"
    weight = 9

[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # 是否展示代码行数
    lineNos = true
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Hugo 输出文档的设置（搜索要用到）
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 用于分类的设置
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  # Hugo 支持自定义 taxonomy，但 DoIt 主题没有支持自定义 taxonomy 的渲染，先不添加了

# 配合 Obsidian，需要对目录重新映射
[module]
# 渲染时忽略 obsidian 文件
# 经测试，点开头的目录不会被打包，不用添加到这里了
# glob 与正则写法不同。若要忽略多个目录，需要写成 {folder1,folder2}，注意逗号后不能有空格
[[module.mounts]]
  excludeFiles = 'posts/{template,assets}/*'
  source = 'content'
  target = 'content'
# 映射 assets 目录，以保证图片正常展示
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'content/posts/assets'
  target = 'static/assets'
