baseURL = "https://today-calm.github.io/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "TC 的空间"

theme = "DoIt"

[params]
  [params.header]
    [params.header.title]
      name = "TC 的空间"

  [params.footer]
    enable = true
    # 是否显示 Hugo 和主题信息
    hugo = true
    # 托管服务信息 (支持 HTML 格式)
    hostedOn = '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>' 
    copyright = true
    since = 2023

  # 主页配置
  [params.home]
    [params.home.profile]
      enable = true
      # 主页显示头像的 URL
      # 将你的头像文件放置于 static 或者 assets 目录下
      # 文件路径是相对于 static 或者 assets 目录的
      avatarURL = "/moon.jpg"
      subtitle = "没想好的话"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = false
    [params.home.posts]
      enable = true
      paginate = 5

  # 文章页面配置
  [params.page]
    # 是否使用 ruby 扩展语法
    ruby = false
    # 是否使用 fraction 扩展语法
    fraction = false
    # 是否使用 fontawesome 扩展语法
    fontawesome = false
    # KaTeX 数学公式
    [params.page.math]
      enable = false
    # 相关文章推荐配置
    [params.page.related]
      enable = false
    # 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否保持使用文章前面的静态目录
      # 必须显示指定！
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = false

  [params.search]
    enable = true
    # 搜索引擎的类型 ("algolia", "fuse")
    type = "fuse"
    [params.search.fuse]
      minMatchCharLength = 1

# 作者配置
[author]
  name = " "

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "归档"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 4

[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Hugo 输出文档的设置（搜索要用到）
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 渲染时忽略 obsidian 文件
# https://gohugo.io/getting-started/configuration/#ignore-content-and-data-files-when-rendering
# https://gohugo.io/hugo-modules/configuration/#module-config-mounts
[module]
[[module.mounts]]
  # 经测试，点开头的目录不会被打包，不用添加到这里了
  # glob 与正则写法不同
  # 若要忽略多个目录，需要写成 {folder1,folder2}（逗号后不能空格）
  excludeFiles = 'posts/{template}/*'
  source = 'content'
  target = 'content'
